version: '3'

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5005
    restart: unless-stopped
